/* ============================================================
   data/jogos.js — Banco de jogos do PS2 Know Ledge Hub®
   Cada registro segue o schema documentado no projeto:
   id, titulo, tituloAlt, ano, regiao, genero[], desenvolvedora,
   publicadora, jogadores, descricao, plataformas[], curiosidades[],
   recepcao{nota, fonte}, acessibilidade[], capa{credito, url}, fontes[]

   Não reproduzimos artes de capa oficiais (protegidas por direitos
   autorais dos respectivos publicadores). Em vez disso, cada card
   traz um link direto para a capa oficial na fonte indicada.
   ============================================================ */

const PS2_JOGOS = [
  {
    id: "gow2",
    titulo: "God of War II",
    tituloAlt: null,
    ano: 2007,
    regiao: "Global",
    genero: ["Ação", "Aventura"],
    desenvolvedora: "SCE Santa Monica Studio",
    publicadora: "Sony Computer Entertainment",
    jogadores: "1",
    descricao: "Sequência da saga de Kratos, aprofunda o combate baseado em combos e quebra-cabeças ambientais, sendo lembrado como um dos pontos altos técnicos do fim de vida do console.",
    plataformas: ["PS2", "PS3 (coletânea remasterizada)"],
    curiosidades: ["Um dos últimos grandes exclusivos do PS2 antes da chegada do PS3.", "Utilizou técnicas avançadas de otimização para extrair desempenho extra do hardware."],
    recepcao: { nota: "Aclamado pela crítica especializada da época", fonte: "MobyGames (agregador de notas)" },
    acessibilidade: ["single-player"],
    capa: { credito: "Sony Computer Entertainment", url: "https://www.mobygames.com/game/27089/god-of-war-ii/cover/group-31378/" },
    fontes: [
      { texto: "Wikipedia — God of War II", url: "https://en.wikipedia.org/wiki/God_of_War_II" },
      { texto: "MobyGames", url: "https://www.mobygames.com/game/27089/god-of-war-ii/" }
    ]
  },
  {
    id: "shadow-colossus",
    titulo: "Shadow of the Colossus",
    tituloAlt: "Wanda to Kyozou (Japão)",
    ano: 2005,
    regiao: "Global",
    genero: ["Aventura", "Ação"],
    desenvolvedora: "Team Ico",
    publicadora: "Sony Computer Entertainment",
    jogadores: "1",
    descricao: "Explora um mundo minimalista onde o jogador enfrenta dezesseis colossos gigantes, sendo citado com frequência como referência em design ambiental e trilha sonora.",
    plataformas: ["PS2", "PS3 (remaster)", "PS4 (remake)"],
    curiosidades: ["Compartilha universo com Ico, lançado anteriormente pelo mesmo estúdio.", "Empurrou os limites de desenho de distância do PS2."],
    recepcao: { nota: "Amplamente premiado por crítica especializada", fonte: "Publicações especializadas da época" },
    acessibilidade: ["single-player"],
    capa: { credito: "Sony Computer Entertainment", url: "https://en.wikipedia.org/wiki/Shadow_of_the_Colossus" },
    fontes: [{ texto: "Wikipedia — Shadow of the Colossus", url: "https://en.wikipedia.org/wiki/Shadow_of_the_Colossus" }]
  },
  {
    id: "gt4",
    titulo: "Gran Turismo 4",
    tituloAlt: null,
    ano: 2004,
    regiao: "Global",
    genero: ["Corrida", "Simulação"],
    desenvolvedora: "Polyphony Digital",
    publicadora: "Sony Computer Entertainment",
    jogadores: "1-2",
    descricao: "Simulador de corrida com extenso catálogo de veículos e pistas, reforçando a franquia como vitrine técnica do hardware gráfico do PS2.",
    plataformas: ["PS2"],
    curiosidades: ["Incluiu suporte a widescreen e taxas de quadros elevadas para o padrão da época.", "Um dos jogos mais vendidos da biblioteca do console."],
    recepcao: { nota: "Recepção muito positiva, especialmente pelo realismo gráfico", fonte: "Publicações especializadas" },
    acessibilidade: ["multiplayer local (split-screen)"],
    capa: { credito: "Sony Computer Entertainment", url: "https://en.wikipedia.org/wiki/Gran_Turismo_4" },
    fontes: [{ texto: "Wikipedia — Gran Turismo 4", url: "https://en.wikipedia.org/wiki/Gran_Turismo_4" }]
  },
  {
    id: "mgs3",
    titulo: "Metal Gear Solid 3: Snake Eater",
    tituloAlt: null,
    ano: 2004,
    regiao: "Global",
    genero: ["Ação", "Furtividade"],
    desenvolvedora: "Konami Computer Entertainment Japan",
    publicadora: "Konami",
    jogadores: "1",
    descricao: "Prequela ambientada na Guerra Fria, introduz mecânicas de camuflagem e sobrevivência na selva, sendo referência em narrativa e direção de arte no console.",
    plataformas: ["PS2", "coletâneas posteriores em outras plataformas"],
    curiosidades: ["Trilha sonora e tema de abertura remetem a filmes de espionagem clássicos.", "Elogiado por design de chefes memoráveis."],
    recepcao: { nota: "Aclamado pela crítica, um dos favoritos da geração", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Konami", url: "https://en.wikipedia.org/wiki/Metal_Gear_Solid_3:_Snake_Eater" },
    fontes: [{ texto: "Wikipedia — Metal Gear Solid 3: Snake Eater", url: "https://en.wikipedia.org/wiki/Metal_Gear_Solid_3:_Snake_Eater" }]
  },
  {
    id: "ffx",
    titulo: "Final Fantasy X",
    tituloAlt: null,
    ano: 2001,
    regiao: "Global",
    genero: ["RPG"],
    desenvolvedora: "Square (Square Enix)",
    publicadora: "Square Electronic Arts / Square Enix",
    jogadores: "1",
    descricao: "Primeiro título principal da franquia com dublagem completa e vozes, marcou a transição da série para o 3D totalmente renderizado e narrativa cinematográfica.",
    plataformas: ["PS2", "coletâneas remasterizadas posteriores"],
    curiosidades: ["Introduziu o sistema de progressão em grade (Sphere Grid).", "Um dos títulos mais vendidos da franquia até então."],
    recepcao: { nota: "Recepção extremamente positiva", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Square Enix", url: "https://en.wikipedia.org/wiki/Final_Fantasy_X" },
    fontes: [{ texto: "Wikipedia — Final Fantasy X", url: "https://en.wikipedia.org/wiki/Final_Fantasy_X" }]
  },
  {
    id: "ico",
    titulo: "Ico",
    tituloAlt: null,
    ano: 2001,
    regiao: "Global",
    genero: ["Aventura", "Quebra-cabeça"],
    desenvolvedora: "Team Ico",
    publicadora: "Sony Computer Entertainment",
    jogadores: "1",
    descricao: "Aventura atmosférica minimalista sobre um garoto que guia uma jovem para fora de um castelo misterioso, influente no uso de silêncio e ambientação como narrativa.",
    plataformas: ["PS2", "PS3 (remaster)"],
    curiosidades: ["Tornou-se referência de design mesmo com vendas iniciais modestas.", "Precursor direto de Shadow of the Colossus."],
    recepcao: { nota: "Culto entre crítica e desenvolvedores", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Sony Computer Entertainment", url: "https://en.wikipedia.org/wiki/Ico" },
    fontes: [{ texto: "Wikipedia — Ico", url: "https://en.wikipedia.org/wiki/Ico" }]
  },
  {
    id: "kh",
    titulo: "Kingdom Hearts",
    tituloAlt: null,
    ano: 2002,
    regiao: "Global",
    genero: ["RPG", "Ação"],
    desenvolvedora: "Square (Square Enix)",
    publicadora: "Square Electronic Arts",
    jogadores: "1",
    descricao: "Cruzamento entre universos Disney e Final Fantasy, combinando ação em tempo real com elementos de RPG, iniciando uma franquia duradoura.",
    plataformas: ["PS2", "coletâneas remasterizadas posteriores"],
    curiosidades: ["Resultado de parceria pouco convencional entre Square e Disney.", "Deu origem a diversas sequências em múltiplas plataformas."],
    recepcao: { nota: "Bem recebido pela crítica e público", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Square Enix / Disney", url: "https://en.wikipedia.org/wiki/Kingdom_Hearts_(video_game)" },
    fontes: [{ texto: "Wikipedia — Kingdom Hearts (video game)", url: "https://en.wikipedia.org/wiki/Kingdom_Hearts_(video_game)" }]
  },
  {
    id: "gta-sa",
    titulo: "Grand Theft Auto: San Andreas",
    tituloAlt: null,
    ano: 2004,
    regiao: "Global",
    genero: ["Ação", "Mundo aberto"],
    desenvolvedora: "Rockstar North",
    publicadora: "Rockstar Games",
    jogadores: "1",
    descricao: "Expandiu a fórmula de mundo aberto da franquia com três cidades fictícias interligadas, RPG leve de atributos e trilha sonora extensa licenciada.",
    plataformas: ["PS2", "múltiplas plataformas em relançamentos"],
    curiosidades: ["Um dos jogos mais vendidos de toda a geração do PS2.", "Gerou controvérsia e debate público sobre conteúdo, amplamente noticiado."],
    recepcao: { nota: "Vendas recordes e recepção crítica muito positiva", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Rockstar Games", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto:_San_Andreas" },
    fontes: [{ texto: "Wikipedia — Grand Theft Auto: San Andreas", url: "https://en.wikipedia.org/wiki/Grand_Theft_Auto:_San_Andreas" }]
  },
  {
    id: "okami",
    titulo: "Ōkami",
    tituloAlt: null,
    ano: 2006,
    regiao: "Global",
    genero: ["Aventura", "Ação"],
    desenvolvedora: "Clover Studio",
    publicadora: "Capcom",
    jogadores: "1",
    descricao: "Inspirado em folclore e pintura tradicional japonesa, utiliza o 'Pincel Celestial' como mecânica central para resolver enigmas e combate.",
    plataformas: ["PS2", "relançamentos posteriores em outras plataformas"],
    curiosidades: ["Elogiado por direção de arte em estilo sumi-e.", "Lançado tardiamente no ciclo de vida do console."],
    recepcao: { nota: "Aclamado pela crítica, vendas iniciais modestas", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Capcom", url: "https://en.wikipedia.org/wiki/Ōkami" },
    fontes: [{ texto: "Wikipedia — Ōkami", url: "https://en.wikipedia.org/wiki/Ōkami" }]
  },
  {
    id: "silent-hill-2",
    titulo: "Silent Hill 2",
    tituloAlt: null,
    ano: 2001,
    regiao: "Global",
    genero: ["Terror", "Sobrevivência"],
    desenvolvedora: "Konami Computer Entertainment Tokyo",
    publicadora: "Konami",
    jogadores: "1",
    descricao: "Narrativa psicológica densa e uso de neblina e iluminação para disfarçar limitações técnicas, tornando-se referência no gênero de terror de sobrevivência.",
    plataformas: ["PS2", "coletâneas remasterizadas posteriores"],
    curiosidades: ["O uso de neblina é frequentemente citado como decisão técnica que virou marca registrada.", "Diversos finais alternativos conforme as ações do jogador."],
    recepcao: { nota: "Amplamente considerado um marco do gênero", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Konami", url: "https://en.wikipedia.org/wiki/Silent_Hill_2" },
    fontes: [{ texto: "Wikipedia — Silent Hill 2", url: "https://en.wikipedia.org/wiki/Silent_Hill_2" }]
  },
  {
    id: "ddrmax2",
    titulo: "DDRMAX2: Dance Dance Revolution",
    tituloAlt: null,
    ano: 2003,
    regiao: "América do Norte",
    genero: ["Ritmo", "Festa"],
    desenvolvedora: "Konami",
    publicadora: "Konami",
    jogadores: "1-2",
    descricao: "Título de ritmo com tapete de dança, parte da onda de jogos de festa que ampliou o público do PS2 além do jogador tradicional.",
    plataformas: ["PS2"],
    curiosidades: ["Popularizou periféricos alternativos como tapetes de dança no mercado ocidental.", "Foi a versão norte-americana lançada em setembro de 2003, com lista de músicas própria."],
    recepcao: { nota: "Bem recebido no nicho de jogos de ritmo", fonte: "Publicações especializadas" },
    acessibilidade: ["multiplayer local"],
    capa: { credito: "Konami", url: "https://en.wikipedia.org/wiki/DDRMAX2_Dance_Dance_Revolution" },
    fontes: [{ texto: "Wikipedia — DDRMAX2: Dance Dance Revolution", url: "https://en.wikipedia.org/wiki/DDRMAX2_Dance_Dance_Revolution" }]
  },
  {
    id: "jak-daxter",
    titulo: "Jak and Daxter: The Precursor Legacy",
    tituloAlt: null,
    ano: 2001,
    regiao: "Global",
    genero: ["Plataforma", "Aventura"],
    desenvolvedora: "Naughty Dog",
    publicadora: "Sony Computer Entertainment",
    jogadores: "1",
    descricao: "Plataforma 3D com mundo contínuo sem telas de carregamento entre áreas, demonstrando engenharia de streaming avançada para a época.",
    plataformas: ["PS2", "coletâneas remasterizadas posteriores"],
    curiosidades: ["Mundo aberto sem cortes de carregamento foi um destaque técnico amplamente comentado."],
    recepcao: { nota: "Recepção muito positiva", fonte: "Publicações especializadas" },
    acessibilidade: ["single-player"],
    capa: { credito: "Sony Computer Entertainment", url: "https://en.wikipedia.org/wiki/Jak_and_Daxter:_The_Precursor_Legacy" },
    fontes: [{ texto: "Wikipedia — Jak and Daxter: The Precursor Legacy", url: "https://en.wikipedia.org/wiki/Jak_and_Daxter:_The_Precursor_Legacy" }]
  }
];

if (typeof module !== "undefined" && module.exports) module.exports = PS2_JOGOS;
